[DEFAULT]
; Power control mechanism. Can be rapl or dvfs
control = rapl
; PID controller's default P coefficient
P = 0.40
; PID controller's default I coefficient
I = 0
; PID controller's default D coefficient
D = 0
; Path to power_gov
power_gov_path = /usr/bin/power_gov
; Multiplier for the package power in the power model
power_model_pkg_coefficient = 1.28624736081
; Multiplier for the RAM power in the power model
power_model_ram_coefficient = 1.62596253727
; Bias for power in the model, in watts
power_model_bias_watts = 43.9589792861
; Floor for package power, in watts
min_package_watts = 66
; Ceiling for package power, in watts
max_package_watts = 140

[scc-ya1]
max_processes = 14
; Idle power can be obtained with `Client.py --mode getIdle`
idle_watts = 161.1

[scc-ya2]
max_processes = 14
idle_watts = 137.9

[scc-ya3]
max_processes = 14
idle_watts = 136.5

; scc-z[a-i][1-4] nodes have 14 cores per socket, 2 sockets
[scc-za1]
max_processes = 28
idle_watts = 169

[scc-za2]
max_processes = 28
idle_watts = 168

[scc-za3]
max_processes = 28
idle_watts = 166

[scc-za4]
max_processes = 28
idle_watts = 171

[scc-zb1]
max_processes = 28
idle_watts = 172

[scc-zb2]
max_processes = 28
idle_watts = 169

[scc-zb3]
max_processes = 28
idle_watts = 170

[scc-zb4]
max_processes = 28
idle_watts = 168

[scc-zc1]
max_processes = 28
idle_watts = 175

[scc-zc2]
max_processes = 28
idle_watts = 175

[scc-zc3]
max_processes = 28
idle_watts = 175

[scc-zc4]
max_processes = 28
idle_watts = 171

[scc-zd1]
max_processes = 28
idle_watts = 172

[scc-zd2]
max_processes = 28
idle_watts = 167

[scc-zd3]
max_processes = 28
idle_watts = 169

[scc-zd4]
max_processes = 28
idle_watts = 170

[scc-ze1]
max_processes = 28
idle_watts = 172

[scc-ze2]
max_processes = 28
idle_watts = 170

[scc-ze3]
max_processes = 28
idle_watts = 169

[scc-ze4]
max_processes = 28
idle_watts = 163

[scc-zf1]
max_processes = 28
idle_watts = 171

[scc-zf2]
max_processes = 28
idle_watts = 171

[scc-zf3]
max_processes = 28
idle_watts = 175

[scc-zf4]
max_processes = 28
idle_watts = 168

[scc-zg1]
max_processes = 28
idle_watts = 168

[scc-zg2]
max_processes = 28
idle_watts = 170

[scc-zg3]
max_processes = 28
idle_watts = 171

[scc-zg4]
max_processes = 28
idle_watts = 161

[scc-zh1]
max_processes = 28
idle_watts = 164

[scc-zh2]
max_processes = 28
idle_watts = 168

[scc-zh3]
max_processes = 28
idle_watts = 167

[scc-zh4]
max_processes = 28
idle_watts = 169

[scc-zi1]
max_processes = 28
idle_watts = 166

[scc-zi2]
max_processes = 28
idle_watts = 170

[scc-zi3]
max_processes = 28
idle_watts = 173

[scc-zi4]
max_processes = 28
idle_watts = 170
