[system]
; Expected utilization ratio (or target utilization for simulation runs)
utilization = 0.9
; Communication technique to use: rabbitmq or file
communication = rabbitmq
; Number of seconds to run the master
time_seconds = 10800
; Hostname or IP of the master
master = scc-za1
qos_level = mid

; Names of applications to run. Optionally specify job size as
; application name = job size
[applications]
ep.D.88=4
sp.D.100=4
lu.D.224=8
ft.D.128=6
sp.D.196=8
cg.D.128=6
ep.D.100=4
is.D.64=4

[standby_application]
lu.C.24

; clients controlled by the master node
[clients]
;scc-za1
scc-za2
scc-za3
scc-za4
scc-zb1
scc-zb2
scc-zb3
scc-zb4
scc-zc1
scc-zc2
scc-zc3
scc-zc4
scc-zd1
scc-zd2
scc-zd3
scc-zd4
scc-ze1
scc-ze2
scc-ze3
scc-ze4
scc-zf1
scc-zf2
scc-zf3
scc-zf4
scc-zg1
scc-zg2
scc-zg3
scc-zg4
scc-zh1
scc-zh2
scc-zh3
scc-zh4
scc-zi1
scc-zi2
scc-zi3
scc-zi4

[simulation]
idle_watts = 169
client_count = 500
