; min_job_power_watts: Least amount of power per node consumed while working on a job
; max_job_power_watts: Most power consumed per node while working on a job
; min_time_seconds: Amount of time for the job run without power cap
; max_time_seconds: Amount of time for the job with the tightest power cap
; qos_constraint: QoS constraint.
;     QoS note: Motivate valid ranges by looking at job queue data from any
;     cluster of interest. Q=(T_end - T_submit - T_end_uncapped + T_start_uncapped) /
;                            (T_end_uncapped - T_start_uncapped)
;     Right now we aim for a 90% guarantee, so pick a number less than 90th percentile
;     from your cluster's job queue data.
;     E.g., rrze-traces-emmy-jobs-01.txt from https://doi.org/10.1109/IPDPS47924.2020.00087
;     90% of jobs have qos_degradation < 22.8
[DEFAULT]
job_size = 1

[bt.D.36]
min_job_power_watts = 140
max_job_power_watts = 280
min_time_seconds    = 739
max_time_seconds    = 1211
qos_constraint      = 5.0

[bt.D.81]
min_job_power_watts = 140
max_job_power_watts = 280
min_time_seconds    = 376
max_time_seconds    = 675
job_size = 2
qos_constraint      = 5.0

[bt.D.169]
min_job_power_watts = 140
max_job_power_watts = 280
min_time_seconds    = 179
max_time_seconds    = 317
job_size = 4
qos_constraint      = 5.0

[cg.D.32]
min_job_power_watts = 140
max_job_power_watts = 280
min_time_seconds    = 310
max_time_seconds    = 425
qos_constraint      = 5.0

[ep.D.43]
min_job_power_watts = 140
max_job_power_watts = 280
min_time_seconds    = 47
max_time_seconds    = 62
qos_constraint      = 5.0

[ft.C.32]
min_job_power_watts = 140
max_job_power_watts = 280
min_time_seconds    = 10
max_time_seconds    = 14
qos_constraint      = 5.0

[ft.D.64]
min_job_power_watts = 140
max_job_power_watts = 280
min_time_seconds    = 99
max_time_seconds    = 151
job_size = 2
qos_constraint      = 5.0

[is.D.32]
min_job_power_watts = 140
max_job_power_watts = 220
min_time_seconds    = 26
max_time_seconds    = 31
qos_constraint      = 5.0

[lu.D.42]
min_job_power_watts = 140
max_job_power_watts = 280
min_time_seconds    = 377
max_time_seconds    = 639
qos_constraint      = 5.0

[mg.D.32]
min_job_power_watts = 140
max_job_power_watts = 270
min_time_seconds    = 74
max_time_seconds    = 95
qos_constraint      = 5.0

[mg.D.64]
min_job_power_watts = 140
max_job_power_watts = 280
min_time_seconds    = 30
max_time_seconds    = 43
job_size = 2
qos_constraint      = 5.0

[mg.E.128]
min_job_power_watts = 140
max_job_power_watts = 280
min_time_seconds    = 143
max_time_seconds    = 202
job_size = 4
qos_constraint      = 5.0

[sp.D.36]
min_job_power_watts = 140
max_job_power_watts = 280
min_time_seconds    = 1085
max_time_seconds    = 1324
qos_constraint      = 5.0

[sp.D.81]
min_job_power_watts = 140
max_job_power_watts = 280
min_time_seconds    = 599
max_time_seconds    = 765
qos_constraint      = 5.0
job_size = 2
