[system]
; Expected utilization ratio (or target utilization for simulation runs)
utilization = 0.75
; Number of seconds to run the master
time_seconds = 10800
qos_level = med

; Names of applications to run. Optionally specify job size as
; application name = job size
[applications]
bt.D.81=2
cg.D.32
ep.D.43
ft.D.64=2
is.D.32
lu.D.42
mg.D.32
sp.D.81=2

[simulation]
idle_watts = 169
client_count = 500