[system]
; Expected utilization ratio (or target utilization for simulation runs)
utilization = 0.75
; Number of seconds to run the master
time_seconds = 10800
qos_level = med

; Names of applications to run. Optionally specify job size as
; application name = job size
[applications]
ft.D.64=20
bt.D.81=20
lu.D.42=10

[simulation]
idle_watts = 169
client_count = 500
